use std::cell::RefCell;
use std::collections::HashSet;

// use ark_bls12_377::{Bls12_377, G2Projective};
use ark_bls12_381::{G2Projective, Bls12_381};
use ark_ec::AffineRepr;
use ark_serialize::CanonicalSerialize;
use ark_std::{end_timer, start_timer, test_rng};
use w3f_pcs::pcs::PcsParams;
use merlin::Transcript;
use rand::Rng;
use apk_proofs::bls::{PublicKey, SecretKey, Signature};
use apk_proofs::instances::bls12_381_bw6_767::kzg::*;
use apk_proofs::instances::bls12_381_bw6_767::*;
use apk_proofs::{hash_to_curve, setup, Bitmask};

// This example sketches the primary intended use case of the crate functionality:
// building communication-efficient light clients for blockchains.

#[derive(Clone)]
struct Validator(SecretKey<Bls12_381>);

struct Approval {
    comm: KeysetCommitment381,
    sig: Signature<Bls12_381>,
    pk: PublicKey<Bls12_381>,
}

thread_local! {
    static CACHE: RefCell<Option<KeysetCommitment381>> = RefCell::new(None);
}

fn new_era() {
    CACHE.with(|cell| {
        cell.replace(None);
    });
}

fn get_keyset_commitment<F>(f: F) -> KeysetCommitment381
where
    F: FnOnce() -> KeysetCommitment381,
{
    CACHE.with(|cell| {
        let mut cell = cell.borrow_mut();
        let old_opt = cell.as_ref();
        match old_opt {
            None => {
                let new_val = f();
                let new_opt = Some(new_val.clone());
                *cell = new_opt;
                new_val
            }
            Some(val) => val.clone(),
        }
    })
}

impl Validator {
    fn new<R: Rng>(rng: &mut R) -> Self {
        Self(SecretKey::new(rng))
    }

    fn public_key(&self) -> PublicKey<Bls12_381> {
        PublicKey::from(&self.0)
    }

    fn approve(
        &self,
        new_validator_set: &ValidatorSet,
        pcs_params: &<Pcs as w3f_pcs::pcs::PCS<OuterScalar>>::Params,
    ) -> Approval {
        // Computing the commitment to the new validator set is a time consuming operation.
        // In real-world deployments it is run by each validator, hence in parallel.
        // We model that by sharing the commitment generated by the first validator among others.
        let new_validator_set_commitment = get_keyset_commitment(|| {
            Keyset381::new(new_validator_set.raw_public_keys()).commit::<Pcs>(&pcs_params.ck())
        });
        let message = hash_commitment(&new_validator_set_commitment);
        Approval {
            comm: new_validator_set_commitment,
            sig: self.0.sign(&message),
            pk: self.public_key(),
        }
    }
}

#[derive(Clone)]
struct ValidatorSet {
    validators: Vec<Validator>,
    quorum: usize,
}

impl ValidatorSet {
    fn new<R: Rng>(size: usize, quorum: usize, rng: &mut R) -> Self {
        let validators = (0..size).map(|_| Validator::new(rng)).collect();
        Self { validators, quorum }
    }

    fn public_keys(&self) -> Vec<PublicKey<Bls12_381>> {
        self.validators.iter().map(|v| v.public_key()).collect()
    }

    fn raw_public_keys(&self) -> Vec<InnerCurve> {
        self.public_keys().iter().map(|pk| pk.as_group().clone()).collect()
    }

    fn rotate<R: Rng>(
        &self,
        pcs_params: &<Pcs as w3f_pcs::pcs::PCS<OuterScalar>>::Params,
        rng: &mut R,
    ) -> (ValidatorSet, Vec<Approval>) {
        new_era();
        let new_validator_set = ValidatorSet::new(self.size(), self.quorum, rng);

        let t_approval = start_timer!(|| format!(
            "Each (honest) validator computes the commitment to the new validator set of size {} and signs the commitment",
            new_validator_set.size()
        ));

        let approvals = self
            .validators
            .iter()
            .filter(|_| rng.gen_bool(test_rng().gen_range(6..10) as f64 / 10.0))
            .map(|v| v.approve(&new_validator_set, pcs_params))
            .collect();

        end_timer!(t_approval);
        println!();

        (new_validator_set, approvals)
    }

    fn size(&self) -> usize {
        self.validators.len()
    }
}

struct LightClient {
    rvk: <<Pcs as w3f_pcs::pcs::PCS<OuterScalar>>::Params as PcsParams>::RVK,
    current_validator_set_commitment: KeysetCommitment381,
    quorum: usize,
}

impl LightClient {
    fn init(
        rvk: <<Pcs as w3f_pcs::pcs::PCS<OuterScalar>>::Params as PcsParams>::RVK,
        genesis_keyset_commitment: KeysetCommitment381,
        quorum: usize,
    ) -> Self {
        Self {
            rvk,
            current_validator_set_commitment: genesis_keyset_commitment,
            quorum,
        }
    }

    fn verify_aggregates(
        &mut self,
        public_input: AccountablePublicInput381,
        proof: &SimpleProof381,
        aggregate_signature: &Signature<Bls12_381>,
        new_validator_set_commitment: KeysetCommitment381,
    ) {
        let n_signers = public_input.bitmask.count_ones();
        let t_verification = start_timer!(|| format!(
            "Light client verifies light client proof for {} signers",
            n_signers
        ));

        let t_apk = start_timer!(|| "apk proof verification");
        let verifier = Verifier381::new(
            self.rvk.clone(),
            self.current_validator_set_commitment.clone(),
            Transcript::new(b"apk_proof"),
        );
        assert!(verifier.verify_simple(&public_input, proof));
        end_timer!(t_apk);

        let t_bls = start_timer!(|| "aggregate BLS signature verification");
        let aggregate_public_key = PublicKey::from_group(public_input.apk.into_group());
        let message = hash_commitment(&new_validator_set_commitment);
        assert!(aggregate_public_key.verify(aggregate_signature, &message));
        end_timer!(t_bls);

        assert!(
            n_signers >= self.quorum,
            "{} signers don't make the quorum of {}",
            n_signers,
            self.quorum
        );

        self.current_validator_set_commitment = new_validator_set_commitment;

        end_timer!(t_verification);
    }
}

struct TrustlessHelper {
    pcs_params: <Pcs as w3f_pcs::pcs::PCS<OuterScalar>>::Params,
    current_validator_set: ValidatorSet,
    prover: Prover381,
}

impl TrustlessHelper {
    fn new(
        genesis_validator_set: ValidatorSet,
        genesis_validator_set_commitment: &KeysetCommitment381,
        pcs_params: <Pcs as w3f_pcs::pcs::PCS<OuterScalar>>::Params,
    ) -> Self {
        let prover = Prover381::new(
            Keyset381::new(genesis_validator_set.raw_public_keys()),
            genesis_validator_set_commitment,
            pcs_params.clone(),
            Transcript::new(b"apk_proof"),
        );
        Self {
            pcs_params,
            current_validator_set: genesis_validator_set,
            prover,
        }
    }

    fn aggregate_approvals(
        &mut self,
        new_validator_set: ValidatorSet,
        approvals: Vec<Approval>,
    ) -> (
        AccountablePublicInput381,
        SimpleProof381,
        Signature<Bls12_381>,
        KeysetCommitment381,
    ) {
        let t_approval = start_timer!(|| format!(
            "Helper aggregates {} individual signatures on the same commitment and generates accountable light client proof",
            approvals.len()
        ));

        let new_validator_set_commitment = &approvals[0].comm;
        let actual_signers = approvals.iter().map(|a| &a.pk).collect::<HashSet<_>>();
        let actual_signers_bitmask = self
            .current_validator_set
            .public_keys()
            .iter()
            .map(|pk| actual_signers.contains(pk))
            .collect::<Vec<_>>();

        let (proof, public_input) = self
            .prover
            .prove_simple(Bitmask::from_bits(&actual_signers_bitmask));
        let signatures = approvals.iter().map(|a| &a.sig);
        let aggregate_signature = Signature::aggregate(signatures);

        self.current_validator_set = new_validator_set.clone();
        self.prover = Prover381::new(
            Keyset381::new(new_validator_set.raw_public_keys()),
            new_validator_set_commitment,
            self.pcs_params.clone(),
            Transcript::new(b"apk_proof"),
        );

        end_timer!(t_approval);
        println!();

        (
            public_input,
            proof,
            aggregate_signature,
            new_validator_set_commitment.clone(),
        )
    }
}

fn hash_commitment(commitment: &KeysetCommitment381) -> G2Projective {
    let mut buf = vec![0u8; commitment.compressed_size()];
    commitment
        .serialize_compressed(&mut buf[..])
        .unwrap();
    hash_to_curve(&buf)
}

fn main() {
    let mut args = std::env::args();
    args.next();

    let log_n: usize = args
        .next()
        .unwrap_or("4".to_string())
        .parse()
        .expect("invalid LOG_N");
    let n_eras: usize = args
        .next()
        .unwrap_or("10".to_string())
        .parse()
        .expect("invalid N_ERAS");

    print!(
        "Running a chain with 2^{}-1 validators for {} eras. ",
        log_n, n_eras
    );
    println!("To change the values run with '--example recursive LOG_N N_ERAS'\n");

    let rng = &mut test_rng(); // Don't use in production code!

    println!("Setup: max validator set size = 2^{}-1\n", log_n);

    let t_setup =
        start_timer!(|| format!("Generating PCS params to support 2^{}-1 signers", log_n));
    let pcs_params = setup::generate_for_domain::<_, _, Pcs>(log_n as u32, rng);
    end_timer!(t_setup);

    let keyset_size = (1 << log_n) - 1;
    let quorum = ((keyset_size * 2) / 3) + 1;
    

    println!(
        "\nGenesis: validator set size = {}, quorum = {}\n",
        keyset_size, quorum
    );

    let t_genesis = start_timer!(|| format!(
        "Computing commitment to the set of initial {} validators",
        keyset_size
    ));
    let genesis_validator_set = ValidatorSet::new(keyset_size, quorum, rng);
    let keyset = Keyset381::new(genesis_validator_set.raw_public_keys());
    let genesis_validator_set_commitment = keyset.commit::<Pcs>(&pcs_params.ck());
    end_timer!(t_genesis);

    let mut helper = TrustlessHelper::new(
        genesis_validator_set.clone(),
        &genesis_validator_set_commitment,
        pcs_params.clone(),
    );
    let mut light_client = LightClient::init(
        pcs_params.raw_vk(),
        genesis_validator_set_commitment,
        quorum,
    );

    let mut current_validator_set = genesis_validator_set;

    for era in 1..=n_eras {
        println!("\nEra {}\n", era);
        let (new_validator_set, approvals) = current_validator_set.rotate(&pcs_params, rng);

        let (public_input, proof, aggregate_signature, new_validator_set_commitment) =
            helper.aggregate_approvals(new_validator_set.clone(), approvals);

        light_client.verify_aggregates(
            public_input,
            &proof,
            &aggregate_signature,
            new_validator_set_commitment,
        );

        current_validator_set = new_validator_set;
    }
}