use ark_ff::PrimeField;
use num_bigint::BigUint;

use super::naive::subgroup_generator;
use super::types::{DomainFactory, FftDomain};

/// Prime factors small enough that a direct O(p^2) DFT beats reducing them further.
///
/// The cost model says a radix-p stage costs about `(p-1)^2` multiplications per block, i.e.
/// `(p-1)^2 / p` per output point: 0.5 for p=2, 1.3 for p=3, 9.1 for p=11, 21 for p=23, 45 for
/// p=47. Rader would replace a p-point DFT with two transforms of length >= 2p-3 plus a
/// pointwise product; for p=47 that works out to roughly 3100 multiplications against 2116 for
/// the direct DFT, so direct wins. Rader only pays off for the large factor 10177, where direct
/// would be 103.5M against roughly 3.9M.
const MAX_DIRECT_RADIX: usize = 64;

/// A transform plan: a tree of Cooley-Tukey splits with direct DFTs at the leaves.
///
/// Built once per domain and reused, so all twiddle factors are precomputed.
#[derive(Clone, Debug)]
enum Plan<F: PrimeField> {
    /// Direct O(n^2) DFT over `1, w, ..., w^(n-1)`.
    Direct { n: usize, w: F },
    /// `n = n1 * n2`, transformed as `n1` inner DFTs of length `n2`, a twiddle multiplication,
    /// then `n2` outer DFTs of length `n1`.
    Split {
        n: usize,
        n1: usize,
        n2: usize,
        inner: Box<Plan<F>>,
        outer: Box<Plan<F>>,
        /// `w^(k1 * i2)` for `i2 < n2`, `k1 < n1`, flattened as `i2 * n1 + k1`.
        twiddles: Vec<F>,
    },
}

impl<F: PrimeField> Plan<F> {
    /// Builds a plan for the order-`n` subgroup generated by `w`.
    ///
    /// `factors` is the multiset of prime factors of `n`, smallest first. The split peels off
    /// one factor at a time, so the outer stages use the small radices and the deepest inner
    /// stage the largest; that keeps the long strided passes on the cheap radices.
    fn build(n: usize, w: F, factors: &[usize]) -> Self {
        debug_assert_eq!(factors.iter().product::<usize>(), n);

        if factors.len() <= 1 || n <= MAX_DIRECT_RADIX {
            return Plan::Direct { n, w };
        }

        let n1 = factors[0];
        let n2 = n / n1;
        // w1 generates the order-n1 subgroup, w2 the order-n2 one.
        let w1 = w.pow([n2 as u64]);
        let w2 = w.pow([n1 as u64]);

        let mut twiddles = Vec::with_capacity(n);
        for i2 in 0..n2 {
            let mut t = F::one();
            let step = w.pow([i2 as u64]);
            for _ in 0..n1 {
                twiddles.push(t);
                t *= step;
            }
        }

        Plan::Split {
            n,
            n1,
            n2,
            inner: Box::new(Plan::build(n2, w2, &factors[1..])),
            outer: Box::new(Plan::Direct { n: n1, w: w1 }),
            twiddles,
        }
    }

    /// Evaluates `coeffs` (zero-padded to the plan's size) over the plan's domain.
    fn eval(&self, coeffs: &[F]) -> Vec<F> {
        match self {
            Plan::Direct { n, w } => {
                let mut out = Vec::with_capacity(*n);
                let mut point = F::one();
                for _ in 0..*n {
                    out.push(coeffs.iter().rev().fold(F::zero(), |acc, &c| acc * point + c));
                    point *= *w;
                }
                out
            }
            Plan::Split { n, n1, n2, inner, outer, twiddles } => {
                let mut padded;
                let coeffs = if coeffs.len() < *n {
                    padded = coeffs.to_vec();
                    padded.resize(*n, F::zero());
                    &padded
                } else {
                    coeffs
                };

                // Inner DFTs over the decimated sub-sequences a[k1], a[k1 + n1], ...
                let mut inner_dfts = Vec::with_capacity(*n1);
                for k1 in 0..*n1 {
                    let sub: Vec<F> = coeffs.iter().skip(k1).step_by(*n1).cloned().collect();
                    debug_assert_eq!(sub.len(), *n2);
                    inner_dfts.push(inner.eval(&sub));
                }

                let mut result = vec![F::zero(); *n];
                let mut outer_coeffs = vec![F::zero(); *n1];
                for i2 in 0..*n2 {
                    for k1 in 0..*n1 {
                        outer_coeffs[k1] = twiddles[i2 * n1 + k1] * inner_dfts[k1][i2];
                    }
                    let outer_dft = outer.eval(&outer_coeffs);
                    for i1 in 0..*n1 {
                        result[i1 * n2 + i2] = outer_dft[i1];
                    }
                }
                result
            }
        }
    }
}

/// Factors `n` by trial division. `n` here is a domain size, at most a few hundred thousand,
/// so this is not worth doing cleverly.
fn prime_factors(mut n: usize) -> Vec<usize> {
    let mut factors = Vec::new();
    let mut d = 2;
    while d * d <= n {
        while n % d == 0 {
            factors.push(d);
            n /= d;
        }
        d += if d == 2 { 1 } else { 2 };
    }
    if n > 1 {
        factors.push(n);
    }
    factors
}

/// A mixed-radix Cooley-Tukey evaluation domain.
///
/// Handles any `n` dividing `q - 1` whose prime factors are individually small enough for a
/// direct DFT. Over BW6-767's scalar field that covers every divisor of
/// `2 * 3^2 * 11 * 23 * 47 = 214038` — comfortably past any realistic validator count, since
/// Polkadot and Kusama run on the order of a thousand. The one remaining usable factor, 10177,
/// needs Rader's algorithm and only becomes necessary above roughly 53,500 validators.
#[derive(Clone, Debug)]
pub struct CooleyTukeyDomain<F: PrimeField> {
    size: usize,
    w: F,
    w_inv: F,
    size_inv: F,
    fwd: Plan<F>,
    inv: Plan<F>,
}

impl<F: PrimeField> CooleyTukeyDomain<F> {
    /// Returns `None` if `F*` has no subgroup of order `size`, or if any prime factor of `size`
    /// is too large for a direct DFT (those need Rader).
    pub fn new(size: usize) -> Option<Self> {
        let w = subgroup_generator::<F>(size)?;
        let w_inv = w.inverse()?;
        let size_inv = F::from(size as u64).inverse()?;

        let factors = prime_factors(size);
        if factors.iter().any(|&p| p > MAX_DIRECT_RADIX) && factors.len() > 1 {
            return None;
        }

        Some(CooleyTukeyDomain {
            size,
            w,
            w_inv,
            size_inv,
            fwd: Plan::build(size, w, &factors),
            inv: Plan::build(size, w_inv, &factors),
        })
    }
}

/// An upper bound on the domain sizes worth enumerating.
///
/// Only needed to keep the search finite for 2-adic fields, where the smooth part of `q - 1` is
/// astronomically large: BW6-761's contains 2^46 on its own. It is far above any size the
/// prover could afford to transform.
const MAX_ADMISSIBLE_SIZE: usize = 1 << 32;

/// The prime powers `p^e || q - 1` for primes small enough to transform directly.
///
/// Trial division by every integer up to the radix bound is correct without a primality test,
/// since a composite's prime factors are removed before it is reached.
fn usable_prime_powers<F: PrimeField>() -> Vec<(usize, u32)> {
    let mut order: BigUint = Into::<BigUint>::into(F::MODULUS) - 1u8;
    let mut powers = Vec::new();
    for p in 2..=MAX_DIRECT_RADIX {
        let big_p = BigUint::from(p);
        let mut e = 0;
        while (&order % &big_p) == BigUint::from(0u32) {
            order /= &big_p;
            e += 1;
        }
        if e > 0 {
            powers.push((p, e));
        }
    }
    powers
}

/// Every domain size this backend can build, ascending.
///
/// These are the divisors of the usable smooth part of `q - 1`. For BW6-767's scalar field that
/// is `2 * 3^2 * 11 * 23 * 47 = 214038`, so 48 sizes — the sparseness is a property of the
/// field, not of this code, and is why a caller asking for `n` can be handed noticeably more.
pub fn admissible_sizes<F: PrimeField>(max: usize) -> Vec<usize> {
    let max = max.min(MAX_ADMISSIBLE_SIZE);
    let mut sizes = vec![1usize];
    for (p, e) in usable_prime_powers::<F>() {
        let mut next = Vec::new();
        for &s in &sizes {
            let mut v = s;
            for _ in 0..=e {
                if v > max {
                    break;
                }
                next.push(v);
                v = v.saturating_mul(p);
            }
        }
        next.sort_unstable();
        next.dedup();
        sizes = next;
    }
    sizes
}

impl<F: PrimeField> CooleyTukeyDomain<F> {
    /// The smallest constructible domain of at least `min_size`.
    ///
    /// Returns `None` when the field offers no such size, which for BW6-767 happens above
    /// roughly 53,500: the largest 10177-free divisor of `q - 1` is 214038, and the PIOP needs
    /// a domain of at least `4n - 2`. Getting past that needs Rader's algorithm for the 10177
    /// factor.
    pub fn smallest_at_least(min_size: usize) -> Option<Self> {
        let ceiling = min_size.saturating_mul(64).max(1024);
        admissible_sizes::<F>(ceiling)
            .into_iter()
            .find(|&n| n >= min_size)
            .and_then(Self::new)
    }
}

impl<F: PrimeField> DomainFactory<F> for CooleyTukeyDomain<F> {
    fn create_domain(size: usize) -> Self {
        Self::smallest_at_least(size).unwrap_or_else(|| {
            panic!(
                "this field has no transformable domain of size >= {}; the largest available is {:?}",
                size,
                admissible_sizes::<F>(MAX_ADMISSIBLE_SIZE).last()
            )
        })
    }
}

impl<F: PrimeField> FftDomain<F> for CooleyTukeyDomain<F> {
    fn size(&self) -> usize {
        self.size
    }

    fn generator(&self) -> F {
        self.w
    }

    fn generator_inv(&self) -> F {
        self.w_inv
    }

    fn size_inv(&self) -> F {
        self.size_inv
    }

    fn fft(&self, coeffs: &[F]) -> Vec<F> {
        assert!(coeffs.len() <= self.size, "more coefficients than domain points");
        self.fwd.eval(coeffs)
    }

    fn interpolate(&self, evals: &[F]) -> Vec<F> {
        assert_eq!(evals.len(), self.size, "interpolation needs exactly `size` evaluations");
        let mut coeffs = self.inv.eval(evals);
        coeffs.iter_mut().for_each(|c| *c *= self.size_inv);
        coeffs
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::NaiveDomain;
    use crate::Radix2Domain;
    use ark_std::{test_rng, UniformRand};

    type Fr767 = ark_bw6_767::Fr;
    type Fr761 = ark_bw6_761::Fr;

    #[test]
    fn factors_correctly() {
        assert_eq!(prime_factors(1551), vec![3, 11, 47]);
        assert_eq!(prime_factors(9306), vec![2, 3, 3, 11, 47]);
        assert_eq!(prime_factors(214038), vec![2, 3, 3, 11, 23, 47]);
        assert_eq!(prime_factors(10177), vec![10177]);
        assert_eq!(prime_factors(256), vec![2; 8]);
    }

    /// The whole justification for this domain: it must agree with the direct DFT everywhere.
    #[test]
    fn agrees_with_naive_dft() {
        let rng = &mut test_rng();
        for n in [253usize, 414, 1081, 1551, 2277] {
            let ct = CooleyTukeyDomain::<Fr767>::new(n).unwrap_or_else(|| panic!("no domain of size {}", n));
            let naive = NaiveDomain::<Fr767>::new(n).unwrap();
            assert_eq!(ct.generator(), naive.generator(), "generators differ at n = {}", n);

            let coeffs: Vec<Fr767> = (0..n).map(|_| Fr767::rand(rng)).collect();
            assert_eq!(ct.fft(&coeffs), naive.fft(&coeffs), "fft differs at n = {}", n);

            let evals: Vec<Fr767> = (0..n).map(|_| Fr767::rand(rng)).collect();
            assert_eq!(
                ct.interpolate(&evals),
                naive.interpolate(&evals),
                "interpolate differs at n = {}", n
            );
        }
    }

    /// Also agrees with arkworks on power-of-two sizes, which exercises the radix-2 path.
    #[test]
    fn agrees_with_radix2_on_powers_of_two() {
        let rng = &mut test_rng();
        let n = 256;
        let ct = CooleyTukeyDomain::<Fr761>::new(n).unwrap();
        let radix2 = Radix2Domain::<Fr761>::new(n);

        let coeffs: Vec<Fr761> = (0..n).map(|_| Fr761::rand(rng)).collect();
        assert_eq!(ct.fft(&coeffs), radix2.fft(&coeffs));

        let evals: Vec<Fr761> = (0..n).map(|_| Fr761::rand(rng)).collect();
        assert_eq!(ct.interpolate(&evals), radix2.interpolate(&evals));
    }

    #[test]
    fn roundtrips() {
        let rng = &mut test_rng();
        for n in [1551usize, 2277, 9306] {
            let domain = CooleyTukeyDomain::<Fr767>::new(n).unwrap();
            let evals: Vec<Fr767> = (0..n).map(|_| Fr767::rand(rng)).collect();
            assert_eq!(domain.fft(&domain.interpolate(&evals)), evals, "roundtrip failed at n = {}", n);
        }
    }

    /// Amplification zero-pads: a degree < m polynomial evaluated over a larger domain.
    #[test]
    fn accepts_short_coefficient_slices() {
        let rng = &mut test_rng();
        let small = CooleyTukeyDomain::<Fr767>::new(253).unwrap();
        let large = CooleyTukeyDomain::<Fr767>::new(1551).unwrap();
        let naive_large = NaiveDomain::<Fr767>::new(1551).unwrap();

        let evals: Vec<Fr767> = (0..253).map(|_| Fr767::rand(rng)).collect();
        let coeffs = small.interpolate(&evals);
        assert_eq!(large.fft(&coeffs), naive_large.fft(&coeffs));
    }

    #[test]
    fn rejects_sizes_needing_rader() {
        // 10177 is prime and far too large for a direct DFT; it needs Rader.
        assert!(CooleyTukeyDomain::<Fr767>::new(2 * 10177).is_none());
        // ...and sizes that are not subgroup orders at all.
        assert!(CooleyTukeyDomain::<Fr767>::new(4).is_none());
    }
}

#[cfg(test)]
mod perf {
    use super::*;
    use crate::domain::NaiveDomain;
    use ark_std::{test_rng, UniformRand};
    use std::time::Instant;

    type Fr767 = ark_bw6_767::Fr;

    /// Informational, not a gate: reports the speedup over the direct DFT so a silent fallback
    /// to O(n^2) is visible. Run with `cargo test -- --ignored --nocapture`.
    #[test]
    #[ignore = "timing-dependent; informational"]
    fn report_speedup_over_naive() {
        let rng = &mut test_rng();
        for n in [1551usize, 2277, 9306] {
            let coeffs: Vec<Fr767> = (0..n).map(|_| Fr767::rand(rng)).collect();
            let ct = CooleyTukeyDomain::<Fr767>::new(n).unwrap();
            let naive = NaiveDomain::<Fr767>::new(n).unwrap();

            let t = Instant::now();
            let a = ct.fft(&coeffs);
            let ct_us = t.elapsed().as_micros();

            let t = Instant::now();
            let b = naive.fft(&coeffs);
            let naive_us = t.elapsed().as_micros();

            assert_eq!(a, b);
            println!(
                "n = {:>6}: cooley-tukey {:>8} us, naive {:>9} us, speedup {:.1}x",
                n, ct_us, naive_us, naive_us as f64 / ct_us as f64
            );
        }
    }
}
