use ark_ff::PrimeField;
use num_bigint::BigUint;

use super::subgroup::subgroup_generator;
use super::types::{evaluate_at_powers, FftDomain};

/// The largest prime factor transformed by a naive O(p^2) DFT; larger primes go through Rader.
///
/// On BW6-767's scalar field the usable primes are 2, 3, 11, 23, 47 and 10177, so any bound
/// from 47 to 10176 behaves the same; 64 is a round number in that gap.
const MAX_NAIVE_RADIX: usize = 64;

/// A transform plan: a tree of Cooley-Tukey splits with naive DFTs, or Rader, at the leaves.
///
/// Built once per domain and reused, so all twiddle factors are precomputed.
#[derive(Clone, Debug)]
enum Plan<F: PrimeField> {
    /// Naive O(n^2) DFT over `1, w, ..., w^(n-1)`.
    Naive { n: usize, w: F },
    /// `n = n1 * n2`, transformed as `n1` inner DFTs of length `n2`, a twiddle multiplication,
    /// then `n2` outer DFTs of length `n1`.
    Split {
        n: usize,
        n1: usize,
        n2: usize,
        inner: Box<Plan<F>>,
        outer: Box<Plan<F>>,
        /// `w^(k1 * i2)` for `i2 < n2`, `k1 < n1`, flattened as `i2 * n1 + k1`.
        twiddles: Vec<F>,
    },
    /// Rader's algorithm for a prime `p` too large to transform directly.
    ///
    /// The non-zero indices `1..p` form a cyclic group under multiplication mod `p`, so
    /// reindexing by powers of a primitive root turns the size-`p` DFT into a cyclic
    /// convolution of length `p - 1`, which a pair of transforms over a *different* domain
    /// computes. That domain has to be at least `2p - 3` long here, because `p - 1` itself is
    /// not available: for `p = 10177`, `p - 1 = 2^6 * 3 * 53` does not divide `q - 1`.
    Rader {
        p: usize,
        /// `g^i mod p` for `i < p - 1`, where `g` is a primitive root mod `p`.
        perm: Vec<usize>,
        /// The transformed convolution kernel, pre-scaled by `1 / |conv|` so the inverse
        /// transform below needs no normalisation.
        b_hat: Vec<F>,
        conv: Box<Plan<F>>,
        conv_inv: Box<Plan<F>>,
    },
}

impl<F: PrimeField> Plan<F> {
    fn size(&self) -> usize {
        match self {
            Plan::Naive { n, .. } => *n,
            Plan::Split { n, .. } => *n,
            Plan::Rader { p, .. } => *p,
        }
    }

    /// Builds a plan for the order-`n` subgroup generated by `w`.
    ///
    /// `factors` is the multiset of prime factors of `n`, smallest first. The split peels off
    /// one factor at a time, so the outer stages use the small radices and the deepest inner
    /// stage the largest; that keeps the long strided passes on the cheap radices.
    fn build(n: usize, w: F, factors: &[usize]) -> Option<Self> {
        debug_assert_eq!(factors.iter().product::<usize>(), n);

        // Only a single prime factor bottoms out. A composite always splits, however small:
        // `MAX_NAIVE_RADIX` bounds the largest *prime* worth transforming naively, and using
        // it as a recursion cutoff too would end a power-of-two chain in a 64-point O(n^2) DFT
        // (63^2 multiplications) where six more radix-2 stages cost about 192.
        if factors.len() <= 1 {
            if n <= MAX_NAIVE_RADIX {
                return Some(Plan::Naive { n, w });
            }
            return Self::build_rader(n, w);
        }

        let n1 = factors[0];
        let n2 = n / n1;
        // w1 generates the order-n1 subgroup, w2 the order-n2 one.
        let w1 = w.pow([n2 as u64]);
        let w2 = w.pow([n1 as u64]);

        let mut twiddles = Vec::with_capacity(n);
        for i2 in 0..n2 {
            let mut t = F::one();
            let step = w.pow([i2 as u64]);
            for _ in 0..n1 {
                twiddles.push(t);
                t *= step;
            }
        }

        Some(Plan::Split {
            n,
            n1,
            n2,
            inner: Box::new(Plan::build(n2, w2, &factors[1..])?),
            outer: Box::new(Plan::Naive { n: n1, w: w1 }),
            twiddles,
        })
    }

    /// Reduces a size-`p` DFT to a cyclic convolution of length `p - 1`.
    ///
    /// Returns `None` when the field offers no usable convolution domain. That domain must be at
    /// least `2p - 3` long, must divide `q - 1`, and must not be a multiple of `p` — and it is
    /// held to factors of at most `MAX_NAIVE_RADIX`, so its plan has only naive leaves and this
    /// cannot recurse.
    fn build_rader(p: usize, w: F) -> Option<Self> {
        let g = primitive_root_mod(p)?;
        let n = p - 1;
        let mut perm = vec![1usize; n];
        for i in 1..n {
            perm[i] = perm[i - 1] * g % p;
        }

        let min_conv = 2 * p - 3;
        let m = admissible_sizes_bounded::<F>(MAX_NAIVE_RADIX, min_conv.saturating_mul(64))
            .into_iter()
            .find(|&m| m >= min_conv && m % p != 0)?;
        let w_m = subgroup_generator::<F>(m)?;
        let m_factors = prime_factors(m);
        let conv = Self::build(m, w_m, &m_factors)?;
        let conv_inv = Self::build(m, w_m.inverse()?, &m_factors)?;

        // b[i] = w^(g^(-i)); the kernel of the convolution, transformed once here and reused.
        let mut ws = vec![F::one(); p];
        for i in 1..p {
            ws[i] = ws[i - 1] * w;
        }
        let mut b = vec![w; n];
        for i in 1..n {
            b[i] = ws[perm[n - i]];
        }
        b.resize(m, F::zero());
        let mut b_hat = conv.eval(&b);
        let m_inv = F::from(m as u64).inverse()?;
        b_hat.iter_mut().for_each(|x| *x *= m_inv);

        Some(Plan::Rader {
            p,
            perm,
            b_hat,
            conv: Box::new(conv),
            conv_inv: Box::new(conv_inv),
        })
    }

    /// Evaluates `coeffs` (zero-padded to the plan's size) over the plan's domain.
    fn eval(&self, coeffs: &[F]) -> Vec<F> {
        match self {
            Plan::Naive { n, w } => evaluate_at_powers(coeffs, *w, *n),
            Plan::Split {
                n,
                n1,
                n2,
                inner,
                outer,
                twiddles,
            } => {
                let mut padded;
                let coeffs = if coeffs.len() < *n {
                    padded = coeffs.to_vec();
                    padded.resize(*n, F::zero());
                    &padded
                } else {
                    coeffs
                };

                // Inner DFTs over the decimated sub-sequences a[k1], a[k1 + n1], ...
                let mut inner_dfts = Vec::with_capacity(*n1);
                for k1 in 0..*n1 {
                    let sub: Vec<F> = coeffs.iter().skip(k1).step_by(*n1).cloned().collect();
                    debug_assert_eq!(sub.len(), *n2);
                    inner_dfts.push(inner.eval(&sub));
                }

                let mut result = vec![F::zero(); *n];
                let mut outer_coeffs = vec![F::zero(); *n1];
                for i2 in 0..*n2 {
                    for k1 in 0..*n1 {
                        outer_coeffs[k1] = twiddles[i2 * n1 + k1] * inner_dfts[k1][i2];
                    }
                    let outer_dft = outer.eval(&outer_coeffs);
                    for i1 in 0..*n1 {
                        result[i1 * n2 + i2] = outer_dft[i1];
                    }
                }
                result
            }
            Plan::Rader {
                p,
                perm,
                b_hat,
                conv,
                conv_inv,
            } => {
                let mut padded;
                let coeffs = if coeffs.len() < *p {
                    padded = coeffs.to_vec();
                    padded.resize(*p, F::zero());
                    &padded
                } else {
                    coeffs
                };

                let n = p - 1;
                let m = conv.size();

                // Reindex by powers of the primitive root, then wrap the sequence so the
                // linear convolution the transforms compute agrees with the cyclic one.
                let mut a: Vec<F> = (0..n).map(|i| coeffs[perm[i]]).collect();
                if m > n {
                    a.resize(m - (n - 1), F::zero());
                    a.extend_from_within(1..n);
                }
                debug_assert_eq!(a.len(), m);

                let a_hat = conv.eval(&a);
                let product: Vec<F> = a_hat
                    .into_iter()
                    .zip(b_hat.iter())
                    .map(|(a, b)| a * b)
                    .collect();
                let c = conv_inv.eval(&product);

                let mut result = vec![F::zero(); *p];
                result[0] = coeffs.iter().copied().sum();
                result[1] = coeffs[0] + c[0];
                for i in 1..n {
                    result[perm[n - i]] = coeffs[0] + c[i];
                }
                result
            }
        }
    }
}

/// The smallest primitive root modulo the prime `p`.
fn primitive_root_mod(p: usize) -> Option<usize> {
    if p < 2 {
        return None;
    }
    let factors: Vec<usize> = {
        let mut f = prime_factors(p - 1);
        f.dedup();
        f
    };
    let pow_mod = |mut base: u128, mut exp: u128, m: u128| -> u128 {
        let mut acc = 1u128;
        base %= m;
        while exp > 0 {
            if exp & 1 == 1 {
                acc = acc * base % m;
            }
            base = base * base % m;
            exp >>= 1;
        }
        acc
    };
    (2..p).find(|&g| {
        factors
            .iter()
            .all(|&q| pow_mod(g as u128, ((p - 1) / q) as u128, p as u128) != 1)
    })
}

/// Factors `n` by trial division. `n` here is a domain size, at most a few hundred thousand,
/// so this is not worth doing cleverly.
fn prime_factors(mut n: usize) -> Vec<usize> {
    let mut factors = Vec::new();
    let mut d = 2;
    while d * d <= n {
        while n % d == 0 {
            factors.push(d);
            n /= d;
        }
        d += if d == 2 { 1 } else { 2 };
    }
    if n > 1 {
        factors.push(n);
    }
    factors
}

/// A mixed-radix Cooley-Tukey evaluation domain.
///
/// Handles any `n` dividing `q - 1` whose prime factors are each either small enough for a
/// naive DFT (at most `MAX_NAIVE_RADIX`) or reachable by Rader's algorithm.
#[derive(Clone, Debug)]
pub struct CooleyTukeyDomain<F: PrimeField> {
    size: usize,
    w: F,
    w_inv: F,
    size_inv: F,
    fwd: Plan<F>,
    inv: Plan<F>,
}

impl<F: PrimeField> CooleyTukeyDomain<F> {
    /// Returns `None` if `F*` has no subgroup of order `size`, or if a prime factor of `size`
    /// is too large for a naive DFT and Rader's algorithm finds no usable convolution domain
    /// for it.
    pub fn new(size: usize) -> Option<Self> {
        let w = subgroup_generator::<F>(size)?;
        let w_inv = w.inverse()?;
        let size_inv = F::from(size as u64).inverse()?;

        let factors = prime_factors(size);
        Some(CooleyTukeyDomain {
            size,
            w,
            w_inv,
            size_inv,
            fwd: Plan::build(size, w, &factors)?,
            inv: Plan::build(size, w_inv, &factors)?,
        })
    }
}

/// The prime powers `p^e || q - 1` for primes small enough to transform directly.
///
/// Trial division by every integer up to the radix bound is correct without a primality test,
/// since a composite's prime factors are removed before it is reached.
fn usable_prime_powers<F: PrimeField>(max_prime: usize) -> Vec<(usize, u32)> {
    let mut order: BigUint = Into::<BigUint>::into(F::MODULUS) - 1u8;
    let mut powers = Vec::new();
    for p in 2..=max_prime {
        let big_p = BigUint::from(p);
        let mut e = 0;
        while (&order % &big_p) == BigUint::from(0u32) {
            order /= &big_p;
            e += 1;
        }
        if e > 0 {
            powers.push((p, e));
        }
    }
    powers
}

/// The subgroup orders of `F*` that are at most `max` and whose prime factors are all at most
/// `max_prime`, ascending.
///
/// Only Rader needs this, to find a convolution domain. Which sizes a proof's domains take is
/// not enumerated here but read off a [`crate::DomainSizes`] table, for APK-381
/// [`crate::instances::bls12_381_bw6_767::APK381_DOMAIN_SIZES`].
fn admissible_sizes_bounded<F: PrimeField>(max_prime: usize, max: usize) -> Vec<usize> {
    let mut sizes = vec![1usize];
    for (p, e) in usable_prime_powers::<F>(max_prime) {
        let mut next = Vec::new();
        for &s in &sizes {
            let mut v = s;
            for _ in 0..=e {
                if v > max {
                    break;
                }
                next.push(v);
                v = v.saturating_mul(p);
            }
        }
        next.sort_unstable();
        next.dedup();
        sizes = next;
    }
    sizes
}

impl<F: PrimeField> FftDomain<F> for CooleyTukeyDomain<F> {
    fn size(&self) -> usize {
        self.size
    }

    fn generator(&self) -> F {
        self.w
    }

    fn generator_inv(&self) -> F {
        self.w_inv
    }

    fn size_inv(&self) -> F {
        self.size_inv
    }

    fn fft(&self, coeffs: &[F]) -> Vec<F> {
        assert!(
            coeffs.len() <= self.size,
            "more coefficients than domain points"
        );
        self.fwd.eval(coeffs)
    }

    fn interpolate(&self, evals: &[F]) -> Vec<F> {
        assert_eq!(
            evals.len(),
            self.size,
            "interpolation needs exactly `size` evaluations"
        );
        let mut coeffs = self.inv.eval(evals);
        coeffs.iter_mut().for_each(|c| *c *= self.size_inv);
        coeffs
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::NaiveDomain;
    use crate::Radix2Domain;
    use ark_std::{test_rng, UniformRand};

    type Fr767 = ark_bw6_767::Fr;
    type Fr761 = ark_bw6_761::Fr;

    #[test]
    fn factors_correctly() {
        assert_eq!(prime_factors(1551), vec![3, 11, 47]);
        assert_eq!(prime_factors(9306), vec![2, 3, 3, 11, 47]);
        assert_eq!(prime_factors(214038), vec![2, 3, 3, 11, 23, 47]);
        assert_eq!(prime_factors(10177), vec![10177]);
        assert_eq!(prime_factors(256), vec![2; 8]);
    }

    /// The whole justification for this domain: it must agree with the naive DFT everywhere.
    #[test]
    fn agrees_with_naive_dft() {
        let rng = &mut test_rng();
        for n in [253usize, 414, 1081, 1551, 2277] {
            let ct = CooleyTukeyDomain::<Fr767>::new(n)
                .unwrap_or_else(|| panic!("no domain of size {}", n));
            let naive = NaiveDomain::<Fr767>::new(n).unwrap();
            assert_eq!(
                ct.generator(),
                naive.generator(),
                "generators differ at n = {}",
                n
            );

            let coeffs: Vec<Fr767> = (0..n).map(|_| Fr767::rand(rng)).collect();
            assert_eq!(
                ct.fft(&coeffs),
                naive.fft(&coeffs),
                "fft differs at n = {}",
                n
            );

            let evals: Vec<Fr767> = (0..n).map(|_| Fr767::rand(rng)).collect();
            assert_eq!(
                ct.interpolate(&evals),
                naive.interpolate(&evals),
                "interpolate differs at n = {}",
                n
            );
        }
    }

    /// Also agrees with arkworks on power-of-two sizes, which exercises the radix-2 path.
    #[test]
    fn agrees_with_radix2_on_powers_of_two() {
        let rng = &mut test_rng();
        let n = 256;
        let ct = CooleyTukeyDomain::<Fr761>::new(n).unwrap();
        let radix2 = Radix2Domain::<Fr761>::new(n);

        let coeffs: Vec<Fr761> = (0..n).map(|_| Fr761::rand(rng)).collect();
        assert_eq!(ct.fft(&coeffs), radix2.fft(&coeffs));

        let evals: Vec<Fr761> = (0..n).map(|_| Fr761::rand(rng)).collect();
        assert_eq!(ct.interpolate(&evals), radix2.interpolate(&evals));
    }

    #[test]
    fn roundtrips() {
        let rng = &mut test_rng();
        for n in [1551usize, 2277, 9306] {
            let domain = CooleyTukeyDomain::<Fr767>::new(n).unwrap();
            let evals: Vec<Fr767> = (0..n).map(|_| Fr767::rand(rng)).collect();
            assert_eq!(
                domain.fft(&domain.interpolate(&evals)),
                evals,
                "roundtrip failed at n = {}",
                n
            );
        }
    }

    /// Amplification zero-pads: a degree < m polynomial evaluated over a larger domain.
    #[test]
    fn accepts_short_coefficient_slices() {
        let rng = &mut test_rng();
        let small = CooleyTukeyDomain::<Fr767>::new(253).unwrap();
        let large = CooleyTukeyDomain::<Fr767>::new(1551).unwrap();
        let naive_large = NaiveDomain::<Fr767>::new(1551).unwrap();

        let evals: Vec<Fr767> = (0..253).map(|_| Fr767::rand(rng)).collect();
        let coeffs = small.interpolate(&evals);
        assert_eq!(large.fft(&coeffs), naive_large.fft(&coeffs));
    }

    #[test]
    fn rejects_sizes_that_are_not_subgroup_orders() {
        assert!(CooleyTukeyDomain::<Fr767>::new(4).is_none());
        assert!(CooleyTukeyDomain::<Fr767>::new(5).is_none());
    }

    #[test]
    fn finds_a_primitive_root() {
        // Standard values; a wrong root would silently produce a wrong permutation.
        assert_eq!(primitive_root_mod(3), Some(2));
        assert_eq!(primitive_root_mod(23), Some(5));
        assert_eq!(primitive_root_mod(47), Some(5));
        assert_eq!(primitive_root_mod(10177), Some(7));
    }

    /// Exercises the Rader reduction itself at a size where the naive reference is cheap, by
    /// forcing the path for a prime the planner would otherwise transform directly. The 10177
    /// tests below cover the real size but are too slow for an unoptimised build.
    #[test]
    fn rader_matches_naive_on_a_small_prime() {
        let rng = &mut test_rng();
        let p = 47;
        let w = subgroup_generator::<Fr767>(p).unwrap();
        let rader = Plan::build_rader(p, w).expect("47 has a usable convolution domain");
        assert!(matches!(rader, Plan::Rader { .. }));
        let naive = NaiveDomain::<Fr767>::new(p).unwrap();

        let coeffs: Vec<Fr767> = (0..p).map(|_| Fr767::rand(rng)).collect();
        assert_eq!(rader.eval(&coeffs), naive.fft(&coeffs));
    }

    /// Rader handles the one prime factor of q-1 that is too large to transform directly.
    /// p - 1 = 2^6 * 3 * 53 does not divide q - 1, so the convolution has to be padded to a
    /// domain of at least 2p - 3 = 20351; the smallest available is 23782 = 2 * 11 * 23 * 47.
    #[test]
    #[ignore = "naive reference is 10177^2 ops; run with --release"]
    fn rader_agrees_with_naive_dft_on_10177() {
        let rng = &mut test_rng();
        let p = 10177;
        let rader = CooleyTukeyDomain::<Fr767>::new(p).expect("10177 divides q-1");
        let naive = NaiveDomain::<Fr767>::new(p).unwrap();

        let coeffs: Vec<Fr767> = (0..p).map(|_| Fr767::rand(rng)).collect();
        assert_eq!(rader.fft(&coeffs), naive.fft(&coeffs));
    }

    /// And composes: a domain with 10177 as one factor among several puts a Rader leaf inside
    /// the Cooley-Tukey tree.
    #[test]
    #[ignore = "naive reference is 20354^2 ops; run with --release"]
    fn rader_composes_with_cooley_tukey() {
        let rng = &mut test_rng();
        let n = 2 * 10177;
        let ct = CooleyTukeyDomain::<Fr767>::new(n).expect("2 * 10177 divides q-1");
        let naive = NaiveDomain::<Fr767>::new(n).unwrap();

        let coeffs: Vec<Fr767> = (0..n).map(|_| Fr767::rand(rng)).collect();
        assert_eq!(ct.fft(&coeffs), naive.fft(&coeffs));

        let evals: Vec<Fr767> = (0..n).map(|_| Fr767::rand(rng)).collect();
        assert_eq!(ct.fft(&ct.interpolate(&evals)), evals);
    }
}
